#!/usr/bin/env bash
#displayes bad lack good luck and Best school for 
#number 4 8 and for others

i=0
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else 
		echo "Best school"
	fi
	((i += 1))
done
