#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.

if [ -e "school" ]; then
	echo "school file exists"
	if [ -s "school" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else 
	echo "school file do not exist"
fi
